# version: "1"

# services:
#   node:
#     build: .
#     volumes:
#       - .:/usr/src/app
#     command: sh -c 'yarn start'
#     ports:
#       - 5173:5173
#     environment:
#       - CHOKIDAR_USEPOLLING=true

version: "3.7"
services:
  react:
    build:
      args:
        - NODE_VER=16.17.1-slim
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/home/node/app
    ports:
      - 5173:5173

volumes:
  node_modules:
